
-- CLIENT REGISTRATION ONBOARDING STATUSES

CREATE TABLE client_register (
    clientid        INTEGER     GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    client_category VARCHAR(10) CHECK (client_category IN ('SYSTEM','SELLER','BUYER')),
    client_type     VARCHAR(15) CHECK (client_type IN ('COMPANY','INDIVIDUAL')),
    mobile_primary             VARCHAR(20),
    mobile_primary_verified    BOOLEAN     NOT NULL DEFAULT FALSE,
    mobile_primary_verified_at TIMESTAMPTZ,
    email_primary              VARCHAR(255),
    email_primary_otp          VARCHAR(10),
    email_primary_verified_at  TIMESTAMPTZ,
    address_line1 TEXT,
    address_line2 TEXT,
    city          VARCHAR(100),
    state         VARCHAR(100),
    country       VARCHAR(100) NOT NULL DEFAULT 'India',
    pincode       VARCHAR(10),
    registration_status VARCHAR(40) NOT NULL DEFAULT 'REGISTRATION_STARTED' CHECK (registration_status IN ('REGISTRATION_STARTED','KYC_PENDING','ONBOARDING_COMPLETE')),
    accountstatus VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' CHECK (accountstatus IN ('ACTIVE','INACTIVE','LOCKED')),
    adminusername VARCHAR(100),
    adminuserid   INTEGER,
    created_by INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    updated_by INTEGER
);

CREATE INDEX idx_cr_category_type ON client_register(client_category, client_type);
CREATE INDEX idx_cr_status         ON client_register(registration_status, accountstatus);


-- ============================================================
-- USERS â€” created early so downstream tables can reference it.
-- branchid FK to client_branches is deferred via ALTER TABLE
-- after client_branches is created (avoids circular dependency).
-- ============================================================
CREATE TABLE user_register (
    userid INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    clientid INTEGER NOT NULL REFERENCES client_register(clientid),
    branchid INTEGER,   -- FK added after client_branches via ALTER TABLE below
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(20),
    phone_verified BOOLEAN DEFAULT FALSE,
    phone_verified_at TIMESTAMPTZ,
    password_hash VARCHAR(500) NOT NULL,
    password_salt VARCHAR(100) NOT NULL,
    user_type VARCHAR(25) NOT NULL CHECK (user_type IN ('SYSTEM','SELLER','BUYER')),
    account_status VARCHAR(30) DEFAULT 'ACTIVE' CHECK (account_status IN ('ACTIVE','INACTIVE','LOCKED')),
    is_active BOOLEAN DEFAULT TRUE,
    email_verified BOOLEAN DEFAULT FALSE,
    email_verified_at TIMESTAMPTZ,
    mfa_enabled BOOLEAN DEFAULT FALSE,
    mfa_type VARCHAR(10) CHECK (mfa_type IN ('TOTP','SMS_OTP','EMAIL','NONE')),
    mfa_secret VARCHAR(255),
    force_password_change BOOLEAN DEFAULT TRUE,
    last_login_at TIMESTAMPTZ,
    previous_login_at TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ,
    password_expiry_date TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    deleted_at TIMESTAMPTZ,
    created_by INTEGER REFERENCES user_register(userid),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    updated_by INTEGER
);

CREATE INDEX IF NOT EXISTS idx_users_username       ON user_register(username);
CREATE INDEX IF NOT EXISTS idx_users_email          ON user_register(email);
CREATE INDEX IF NOT EXISTS idx_users_client_id      ON user_register(clientid);
CREATE INDEX IF NOT EXISTS idx_users_account_status ON user_register(account_status);


CREATE TABLE client_company_profile (
    profile_id           INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientid             INTEGER      NOT NULL UNIQUE REFERENCES client_register(clientid) ON DELETE CASCADE,
    company_name         VARCHAR(255) NOT NULL,
    company_name_short   VARCHAR(50),
    company_legal_name   VARCHAR(255),
    company_type         VARCHAR(30)  CHECK (company_type IN ('COOPERATIVE_BANK','FINANCIAL_INSTITUTION','GOVT_BODY','NGO','PRIVATE_LIMITED','PROPRIETORSHIP','PUBLIC_LIMITED','TRUST')),
    website_url          VARCHAR(255),
    establishment_date   DATE,
    incorporation_date   DATE,
    financial_year_start SMALLINT     DEFAULT 4,
    financial_year_end   SMALLINT     DEFAULT 3,
    number_of_employees  INTEGER,
    annual_turnover      DECIMAL(20,2),
    business_category    VARCHAR(100),
    industry_type        VARCHAR(100),
    classification       VARCHAR(100),
    mobile_secondary             VARCHAR(20),
    mobile_secondary_verified    BOOLEAN     NOT NULL DEFAULT FALSE,
    mobile_secondary_verified_at TIMESTAMPTZ,
    fax_number                   VARCHAR(20),
    email_secondary              VARCHAR(255),
    email_secondary_verified     BOOLEAN     NOT NULL DEFAULT FALSE,
    email_secondary_verified_at  TIMESTAMPTZ,
    support_email                VARCHAR(255),
    support_email_verified       BOOLEAN     NOT NULL DEFAULT FALSE,
    support_email_verified_at    TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ,
    updated_by  INTEGER     REFERENCES user_register(userid)
);

CREATE INDEX idx_ccp_clientid ON client_company_profile(clientid);


-- ============================================================
-- DOCUMENT MANAGEMENT
-- ============================================================
CREATE TABLE client_documents (
    doc_id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientid          INTEGER      REFERENCES client_register(clientid) ON DELETE CASCADE,
    user_id           INTEGER      REFERENCES user_register(userid) ON DELETE SET NULL,
    doc_type          VARCHAR(30)  NOT NULL CHECK (doc_type IN ('AADHAAR','PAN_INDIVIDUAL','SELFIE','ADDRESS_PROOF','GST_CERTIFICATE','CIN_CERTIFICATE','PAN_COMPANY','ADDRESS_PROOF_COMP','INCORPORATION_CERT','AUTH_SIGNATORY','BANK_PROOF','OTHER')),
    doc_number_masked VARCHAR(30),
    doc_hash          VARCHAR(64),
    storage_uri       TEXT         NOT NULL,
    file_name         VARCHAR(255),
    file_size_kb      INTEGER,
    mime_type         VARCHAR(100),
    doc_status        VARCHAR(10)  NOT NULL DEFAULT 'PENDING' CHECK (doc_status IN ('EXPIRED','PENDING','VERIFIED')),
    expiry_date       DATE,
    remarks           TEXT,
    uploaded_by       INTEGER      REFERENCES user_register(userid),
    uploaded_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cdoc_client ON client_documents(clientid, doc_type);
CREATE INDEX idx_cdoc_user   ON client_documents(user_id,  doc_type);
CREATE INDEX idx_cdoc_status ON client_documents(doc_status, uploaded_at DESC);
CREATE INDEX idx_cdoc_hash   ON client_documents(doc_hash)  WHERE doc_hash IS NOT NULL;


CREATE TABLE client_user_kyc (
    kyc_id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientid          INTEGER      NOT NULL REFERENCES client_register(clientid) ON DELETE CASCADE,
    user_id           INTEGER      REFERENCES user_register(userid) ON DELETE SET NULL,
    -- FIX: valid kyc_subject values (original had 'SELLER_EMPLOYEE' but check used wrong literals)
    kyc_subject       VARCHAR(20)  NOT NULL CHECK (kyc_subject IN ('SYSTEM_EMPLOYEE','SELLER_COMPANY','SELLER_EMPLOYEE','SELLER_INDIVIDUAL','BUYER_COMPANY','BUYER_INDIVIDUAL')),
    kyc_status        VARCHAR(10)  NOT NULL DEFAULT 'PENDING' CHECK (kyc_status IN ('EXPIRED','PENDING','VERIFIED')),
    gst_masked        VARCHAR(15),
    gst_hash          VARCHAR(64),
    cin_masked        VARCHAR(21),
    cin_hash          VARCHAR(64),
    full_name         VARCHAR(200),
    date_of_birth     DATE,
    pan_masked        VARCHAR(10),
    pan_hash          VARCHAR(64),
    aadhaar_masked    VARCHAR(12),
    aadhaar_hash      VARCHAR(64),
    expiry_date       DATE,
    rejection_reason  TEXT,
    remarks           TEXT,
    submitted_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by        INTEGER      REFERENCES user_register(userid),
    -- FIX: original checked for 'COMPANY' which is not a valid kyc_subject value
    CONSTRAINT chk_kyc_company_no_user CHECK (kyc_subject NOT IN ('SELLER_COMPANY','BUYER_COMPANY') OR user_id IS NULL),
    CONSTRAINT chk_kyc_user_required   CHECK (kyc_subject IN ('SELLER_COMPANY','BUYER_COMPANY')     OR user_id IS NOT NULL)
);

CREATE INDEX idx_cuk_client_subject ON client_user_kyc(clientid, kyc_subject, submitted_at DESC);
CREATE INDEX idx_cuk_user           ON client_user_kyc(user_id,  kyc_subject, submitted_at DESC);
CREATE INDEX idx_cuk_status         ON client_user_kyc(kyc_status, submitted_at DESC);
CREATE INDEX idx_cuk_expiry         ON client_user_kyc(expiry_date) WHERE kyc_status = 'VERIFIED';
CREATE INDEX idx_cuk_pan            ON client_user_kyc(pan_hash)    WHERE pan_hash IS NOT NULL;
CREATE INDEX idx_cuk_aadhaar        ON client_user_kyc(aadhaar_hash) WHERE aadhaar_hash IS NOT NULL;

CREATE TABLE client_logos (
    company_logoid INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    clientid INTEGER NOT NULL UNIQUE REFERENCES client_register(clientid),
    logo_url TEXT NOT NULL,
    logo_file_name VARCHAR(255),
    logo_uploaded_by INTEGER,
    logo_uploaded_at TIMESTAMPTZ,
    banner_url TEXT,
    banner_file_name VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ
);


-- 8. COMPANY BANK ACCOUNTS
CREATE TABLE client_bank_accounts (
    companybankaccountid INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    clientid INTEGER NOT NULL REFERENCES client_register(clientid),
    account_holder_name VARCHAR(255) NOT NULL,
    account_type VARCHAR(15) NOT NULL CHECK (account_type IN ('CURRENT','SAVING')),
    bank_name VARCHAR(255) NOT NULL,
    branch_name VARCHAR(255),
    ifsc_code VARCHAR(20) NOT NULL,
    account_number VARCHAR(30) NOT NULL,
    account_number_encrypted VARCHAR(100),
    is_primary BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    account_verified BOOLEAN DEFAULT FALSE,
    verified_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ
);

-- 2. BRANCH LEVELS (per company)
CREATE TABLE client_branch_levels (
    level_id     INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientid     INTEGER      NOT NULL REFERENCES client_register(clientid) ON DELETE CASCADE,
    level_code   VARCHAR(20)  NOT NULL,
    label        VARCHAR(100) NOT NULL,
    level_order  SMALLINT     NOT NULL CHECK (level_order > 0),
    is_admin_branch BOOLEAN   NOT NULL DEFAULT FALSE,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_on   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by   INTEGER,
    CONSTRAINT uq_client_level_code  UNIQUE (clientid, level_code),
    CONSTRAINT uq_client_level_order UNIQUE (clientid, level_order)
);
CREATE INDEX idx_cbl_client ON client_branch_levels(clientid, level_order);
CREATE UNIQUE INDEX uq_cbl_is_admin_branch ON client_branch_levels(clientid) WHERE is_admin_branch = TRUE;


-- 3. BRANCHES
CREATE TABLE client_branches (
    branchid       INTEGER      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    clientid       INTEGER      NOT NULL REFERENCES client_register(clientid),
    level_id       INTEGER      NOT NULL REFERENCES client_branch_levels(level_id),
    parent_id      INTEGER      REFERENCES client_branches(branchid),
    branch_code    VARCHAR(50)  NOT NULL UNIQUE,
    branch_name    VARCHAR(255) NOT NULL,
    branch_country VARCHAR(100),
    branch_state   VARCHAR(100),
    branch_district VARCHAR(100),
    branch_city    VARCHAR(100),
    branch_address TEXT,
    pin_code       VARCHAR(20),
    phone_primary  VARCHAR(20),
    phone_secondary VARCHAR(20),
    email_primary  VARCHAR(255),
    email_secondary VARCHAR(255),
    status         VARCHAR(30)  DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE','LOCKED')),
    issystemgenerated BOOLEAN   NOT NULL DEFAULT FALSE,
    created_by     INTEGER,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by     INTEGER,
    updated_at     TIMESTAMPTZ
);

-- Deferred FK: user_register.branchid â†’ client_branches
ALTER TABLE user_register
    ADD CONSTRAINT fk_user_branch
    FOREIGN KEY (branchid) REFERENCES client_branches(branchid) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_users_branch_id ON user_register(branchid);


-- ============================================================
-- STAGE 1: USER PROFILES
-- ============================================================
CREATE TABLE user_profiles (
    id                INTEGER      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    userid            INTEGER      NOT NULL UNIQUE REFERENCES user_register(userid),
    first_name        VARCHAR(100),
    middle_name       VARCHAR(100),
    last_name         VARCHAR(100),
    gender            VARCHAR(15)  CHECK (gender IN ('MALE','FEMALE','NON_BINARY','PREFER_NOT_TO_SAY')),
    date_of_birth     DATE,
    profile_photo_url TEXT,
    address_line1 TEXT,
    address_line2 TEXT,
    city          VARCHAR(100),
    state         VARCHAR(100),
    country       VARCHAR(100) NOT NULL DEFAULT 'India',
    pincode       VARCHAR(10),
    alternate_phone   VARCHAR(20),
    designation       VARCHAR(100),
    employee_code     VARCHAR(50),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ,
    updated_by        INTEGER      REFERENCES user_register(userid)
);


-- ============================================================
-- RBAC: MASTER PERMISSIONS
-- ============================================================
CREATE TABLE master_permissions (
    permissionid    INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module          VARCHAR(50)  NOT NULL,
    resource        VARCHAR(50)  NOT NULL,
    action          VARCHAR(30)  NOT NULL,
    permission_code VARCHAR(120) NOT NULL UNIQUE,
    label           VARCHAR(150) NOT NULL,
    description     TEXT,
    applicable_to   VARCHAR(10)  NOT NULL DEFAULT 'ALL' CHECK (applicable_to IN ('SYSTEM','SELLER','BUYER','ALL')),
    is_system       BOOLEAN      NOT NULL DEFAULT TRUE,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order   SMALLINT     NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_perm_code    ON master_permissions(permission_code);
CREATE        INDEX idx_perm_module ON master_permissions(module, applicable_to);
CREATE        INDEX idx_perm_res    ON master_permissions(module, resource);

INSERT INTO master_permissions (module,resource,action,permission_code,label,applicable_to) VALUES
-- â”€â”€ SYSTEM â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
('SYS','CLIENT',    'READ',    'SYS.CLIENT.READ',       'View Client',                'SYSTEM'),
('SYS','CLIENT',    'UPDATE',  'SYS.CLIENT.UPDATE',     'Update Client',              'SYSTEM'),
('SYS','CLIENT',    'BLOCK',   'SYS.CLIENT.BLOCK',      'Block Client',               'SYSTEM'),
('SYS','CLIENT',    'APPROVE', 'SYS.CLIENT.APPROVE',    'Approve Client Onboarding',  'SYSTEM'),
('SYS','CLIENT',    'REJECT',  'SYS.CLIENT.REJECT',     'Reject Client Onboarding',   'SYSTEM'),
('SYS','USER',      'CREATE',  'SYS.USER.CREATE',       'Create Platform User',       'SYSTEM'),
('SYS','USER',      'READ',    'SYS.USER.READ',         'View Platform User',         'SYSTEM'),
('SYS','USER',      'UPDATE',  'SYS.USER.UPDATE',       'Update Platform User',       'SYSTEM'),
('SYS','USER',      'DELETE',  'SYS.USER.DELETE',       'Delete Platform User',       'SYSTEM'),
('SYS','USER',      'BLOCK',   'SYS.USER.BLOCK',        'Block Platform User',        'SYSTEM'),
('SYS','ROLE',      'CREATE',  'SYS.ROLE.CREATE',       'Create System Role',         'SYSTEM'),
('SYS','ROLE',      'READ',    'SYS.ROLE.READ',         'View System Role',           'SYSTEM'),
('SYS','ROLE',      'UPDATE',  'SYS.ROLE.UPDATE',       'Update System Role',         'SYSTEM'),
('SYS','ROLE',      'DELETE',  'SYS.ROLE.DELETE',       'Delete System Role',         'SYSTEM'),
('SYS','PERMISSION','ASSIGN',  'SYS.PERMISSION.ASSIGN', 'Assign System Permission',   'SYSTEM'),
('SYS','PERMISSION','REVOKE',  'SYS.PERMISSION.REVOKE', 'Revoke System Permission',   'SYSTEM'),
('SYS','KYC',       'REVIEW',  'SYS.KYC.REVIEW',        'Review KYC Submission',      'SYSTEM'),
('SYS','KYC',       'APPROVE', 'SYS.KYC.APPROVE',       'Approve KYC',                'SYSTEM'),
('SYS','KYC',       'REJECT',  'SYS.KYC.REJECT',        'Reject KYC',                 'SYSTEM'),
('SYS','AUDIT',     'READ',    'SYS.AUDIT.READ',        'View Audit Log',             'SYSTEM'),
('SYS','AUDIT',     'EXPORT',  'SYS.AUDIT.EXPORT',      'Export Audit Log',           'SYSTEM'),
('SYS','REPORT',    'VIEW',    'SYS.REPORT.VIEW',       'View System Reports',        'SYSTEM'),
('SYS','REPORT',    'EXPORT',  'SYS.REPORT.EXPORT',     'Export System Reports',      'SYSTEM'),
('SYS','PAYMENT',   'READ',    'SYS.PAYMENT.READ',      'View Platform Payments',     'SYSTEM'),
('SYS','PAYMENT',   'EXPORT',  'SYS.PAYMENT.EXPORT',    'Export Platform Payments',   'SYSTEM'),
('SYS','SETTINGS',  'READ',    'SYS.SETTINGS.READ',     'View System Settings',       'SYSTEM'),
('SYS','SETTINGS',  'UPDATE',  'SYS.SETTINGS.UPDATE',   'Update System Settings',     'SYSTEM'),
-- â”€â”€ SELLER â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
('SELLER','BRANCH',   'CREATE', 'SELLER.BRANCH.CREATE',   'Create Branch',            'SELLER'),
('SELLER','BRANCH',   'READ',   'SELLER.BRANCH.READ',     'View Branch',              'SELLER'),
('SELLER','BRANCH',   'UPDATE', 'SELLER.BRANCH.UPDATE',   'Update Branch',            'SELLER'),
('SELLER','BRANCH',   'DELETE', 'SELLER.BRANCH.DELETE',   'Delete Branch',            'SELLER'),
('SELLER','USER',     'CREATE', 'SELLER.USER.CREATE',     'Create Seller User',       'SELLER'),
('SELLER','USER',     'READ',   'SELLER.USER.READ',       'View Seller User',         'SELLER'),
('SELLER','USER',     'UPDATE', 'SELLER.USER.UPDATE',     'Update Seller User',       'SELLER'),
('SELLER','USER',     'DELETE', 'SELLER.USER.DELETE',     'Delete Seller User',       'SELLER'),
('SELLER','USER',     'BLOCK',  'SELLER.USER.BLOCK',      'Block Seller User',        'SELLER'),
('SELLER','ROLE',     'CREATE', 'SELLER.ROLE.CREATE',     'Create Seller Role',       'SELLER'),
('SELLER','ROLE',     'READ',   'SELLER.ROLE.READ',       'View Seller Role',         'SELLER'),
('SELLER','ROLE',     'UPDATE', 'SELLER.ROLE.UPDATE',     'Update Seller Role',       'SELLER'),
('SELLER','ROLE',     'DELETE', 'SELLER.ROLE.DELETE',     'Delete Seller Role',       'SELLER'),
('SELLER','ASSET',    'CREATE', 'SELLER.ASSET.CREATE',    'Create Asset',             'SELLER'),
('SELLER','ASSET',    'READ',   'SELLER.ASSET.READ',      'View Asset',               'SELLER'),
('SELLER','ASSET',    'UPDATE', 'SELLER.ASSET.UPDATE',    'Update Asset',             'SELLER'),
('SELLER','ASSET',    'DELETE', 'SELLER.ASSET.DELETE',    'Delete Asset',             'SELLER'),
('SELLER','ASSET',    'PUBLISH','SELLER.ASSET.PUBLISH',   'Publish Asset',            'SELLER'),
('SELLER','AUCTION',  'CREATE', 'SELLER.AUCTION.CREATE',  'Create Auction',           'SELLER'),
('SELLER','AUCTION',  'READ',   'SELLER.AUCTION.READ',    'View Auction',             'SELLER'),
('SELLER','AUCTION',  'UPDATE', 'SELLER.AUCTION.UPDATE',  'Update Auction',           'SELLER'),
('SELLER','AUCTION',  'DELETE', 'SELLER.AUCTION.DELETE',  'Delete Auction',           'SELLER'),
('SELLER','AUCTION',  'PUBLISH','SELLER.AUCTION.PUBLISH', 'Publish Auction',          'SELLER'),
('SELLER','AUCTION',  'APPROVE','SELLER.AUCTION.APPROVE', 'Approve Auction',          'SELLER'),
('SELLER','LOT',      'CREATE', 'SELLER.LOT.CREATE',      'Create Lot',               'SELLER'),
('SELLER','LOT',      'READ',   'SELLER.LOT.READ',        'View Lot',                 'SELLER'),
('SELLER','LOT',      'UPDATE', 'SELLER.LOT.UPDATE',      'Update Lot',               'SELLER'),
('SELLER','LOT',      'DELETE', 'SELLER.LOT.DELETE',      'Delete Lot',               'SELLER'),
('SELLER','DOCUMENT', 'UPLOAD', 'SELLER.DOCUMENT.UPLOAD', 'Upload Document',          'SELLER'),
('SELLER','DOCUMENT', 'READ',   'SELLER.DOCUMENT.READ',   'View Document',            'SELLER'),
('SELLER','DOCUMENT', 'DELETE', 'SELLER.DOCUMENT.DELETE', 'Delete Document',          'SELLER'),
('SELLER','DOCUMENT', 'APPROVE','SELLER.DOCUMENT.APPROVE','Approve Document',         'SELLER'),
('SELLER','WORKFLOW', 'CREATE', 'SELLER.WORKFLOW.CREATE', 'Create Workflow',          'SELLER'),
('SELLER','WORKFLOW', 'READ',   'SELLER.WORKFLOW.READ',   'View Workflow',            'SELLER'),
('SELLER','WORKFLOW', 'APPROVE','SELLER.WORKFLOW.APPROVE','Approve Workflow Step',    'SELLER'),
('SELLER','WORKFLOW', 'REJECT', 'SELLER.WORKFLOW.REJECT', 'Reject Workflow Step',     'SELLER'),
('SELLER','PAYMENT',  'READ',   'SELLER.PAYMENT.READ',    'View Payments',            'SELLER'),
('SELLER','PAYMENT',  'INITIATE','SELLER.PAYMENT.INITIATE','Initiate Payment',        'SELLER'),
('SELLER','PAYMENT',  'CONFIRM','SELLER.PAYMENT.CONFIRM', 'Confirm Payment',          'SELLER'),
('SELLER','REPORT',   'VIEW',   'SELLER.REPORT.VIEW',     'View Reports',             'SELLER'),
('SELLER','REPORT',   'EXPORT', 'SELLER.REPORT.EXPORT',   'Export Reports',           'SELLER'),
('SELLER','SETTINGS', 'READ',   'SELLER.SETTINGS.READ',   'View Settings',            'SELLER'),
('SELLER','SETTINGS', 'UPDATE', 'SELLER.SETTINGS.UPDATE', 'Update Settings',          'SELLER'),
-- â”€â”€ BUYER â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
('BUYER','USER',     'CREATE',  'BUYER.USER.CREATE',      'Create Buyer User',        'BUYER'),
('BUYER','USER',     'READ',    'BUYER.USER.READ',        'View Buyer User',          'BUYER'),
('BUYER','USER',     'UPDATE',  'BUYER.USER.UPDATE',      'Update Buyer User',        'BUYER'),
('BUYER','USER',     'BLOCK',   'BUYER.USER.BLOCK',       'Block Buyer User',         'BUYER'),
('BUYER','ROLE',     'CREATE',  'BUYER.ROLE.CREATE',      'Create Buyer Role',        'BUYER'),
('BUYER','ROLE',     'READ',    'BUYER.ROLE.READ',        'View Buyer Role',          'BUYER'),
('BUYER','ROLE',     'UPDATE',  'BUYER.ROLE.UPDATE',      'Update Buyer Role',        'BUYER'),
('BUYER','ROLE',     'DELETE',  'BUYER.ROLE.DELETE',      'Delete Buyer Role',        'BUYER'),
('BUYER','BID',      'PLACE',   'BUYER.BID.PLACE',        'Place Bid',                'BUYER'),
('BUYER','BID',      'READ',    'BUYER.BID.READ',         'View Bids',                'BUYER'),
('BUYER','BID',      'RETRACT', 'BUYER.BID.RETRACT',      'Retract Bid',              'BUYER'),
('BUYER','WATCHLIST','ADD',     'BUYER.WATCHLIST.ADD',    'Add to Watchlist',         'BUYER'),
('BUYER','WATCHLIST','READ',    'BUYER.WATCHLIST.READ',   'View Watchlist',           'BUYER'),
('BUYER','WATCHLIST','REMOVE',  'BUYER.WATCHLIST.REMOVE', 'Remove from Watchlist',    'BUYER'),
('BUYER','AUCTION',  'VIEW',    'BUYER.AUCTION.VIEW',     'View Auction',             'BUYER'),
('BUYER','AUCTION',  'REGISTER','BUYER.AUCTION.REGISTER', 'Register for Auction',     'BUYER'),
('BUYER','PAYMENT',  'READ',    'BUYER.PAYMENT.READ',     'View Payments',            'BUYER'),
('BUYER','PAYMENT',  'INITIATE','BUYER.PAYMENT.INITIATE', 'Initiate Payment',         'BUYER'),
('BUYER','PAYMENT',  'CONFIRM', 'BUYER.PAYMENT.CONFIRM',  'Confirm Payment',          'BUYER'),
('BUYER','INVOICE',  'READ',    'BUYER.INVOICE.READ',     'View Invoice',             'BUYER'),
('BUYER','INVOICE',  'DOWNLOAD','BUYER.INVOICE.DOWNLOAD', 'Download Invoice',         'BUYER'),
('BUYER','REPORT',   'VIEW',    'BUYER.REPORT.VIEW',      'View Reports',             'BUYER'),
('BUYER','REPORT',   'EXPORT',  'BUYER.REPORT.EXPORT',    'Export Reports',           'BUYER');

-- ============================================================
-- RBAC: ROLE TEMPLATE SYSTEM
-- ============================================================
CREATE TABLE master_role_templates (
    template_id   INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code VARCHAR(40)  NOT NULL UNIQUE,
    template_name VARCHAR(100) NOT NULL,
    description   TEXT,
    actor_type    VARCHAR(10)  NOT NULL CHECK (actor_type IN ('SYSTEM','SELLER','BUYER')),
    client_type   VARCHAR(10)  NOT NULL DEFAULT 'BOTH' CHECK (client_type IN ('COMPANY','INDIVIDUAL','BOTH')),
    is_system     BOOLEAN      NOT NULL DEFAULT TRUE,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order SMALLINT     NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO master_role_templates (template_code,template_name,description,actor_type,client_type,display_order) VALUES
-- SYSTEM
('SYSTEM_ADMIN',         'System Administrator',  'Full platform control â€” all modules',             'SYSTEM','COMPANY',    1),
('SYSTEM_SUPPORT',       'System Support',        'Read-only + KYC review â€” no write access',        'SYSTEM','COMPANY',    2),
-- SELLER â€” Company
('SELLER_ADMIN',         'Seller Admin',          'Full seller-org control incl. branch & user mgmt','SELLER','COMPANY',   10),
('SELLER_MAKER',         'Seller Maker',          'Initiates assets, auctions, lots, workflows',     'SELLER','COMPANY',   11),
('SELLER_CHECKER',       'Seller Checker',        'Approves or rejects maker-initiated actions',     'SELLER','COMPANY',   12),
('SELLER_VIEWER',        'Seller Viewer',         'Read-only across all seller resources',           'SELLER','COMPANY',   13),
('SELLER_AUDITOR',       'Seller Auditor',        'Read access + full report export',                'SELLER','COMPANY',   14),
('SELLER_FINANCE_ADMIN', 'Seller Finance Admin',  'Payment initiation, confirmation, invoices',      'SELLER','COMPANY',   15),
-- SELLER â€” Individual
('SELLER_INDIVIDUAL',    'Seller Individual',     'All seller rights except branch & team mgmt',     'SELLER','INDIVIDUAL',20),
-- BUYER â€” Company
('BUYER_ADMIN',          'Buyer Admin',           'Full buyer-org control incl. user & role mgmt',  'BUYER', 'COMPANY',   30),
('BUYER_BIDDER',         'Buyer Bidder',          'Place bids, watchlist, register for auctions',    'BUYER', 'COMPANY',   31),
('BUYER_VIEWER',         'Buyer Viewer',          'Read-only â€” auctions, watchlist, reports',        'BUYER', 'COMPANY',   32),
('BUYER_FINANCE_ADMIN',  'Buyer Finance Admin',   'Payment and invoice management',                  'BUYER', 'COMPANY',   33),
('BUYER_AUDITOR',        'Buyer Auditor',         'Read access + full report export',                'BUYER', 'COMPANY',   34),
-- BUYER â€” Individual
('BUYER_INDIVIDUAL',     'Buyer Individual',      'All buyer rights â€” bid, pay, invoice, report',   'BUYER', 'INDIVIDUAL',40);

CREATE TABLE master_role_template_permissions (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id  INTEGER NOT NULL REFERENCES master_role_templates(template_id) ON DELETE CASCADE,
    permissionid INTEGER NOT NULL REFERENCES master_permissions(permissionid)   ON DELETE CASCADE,
    CONSTRAINT uq_tmpl_perm UNIQUE (template_id, permissionid)
);

CREATE INDEX idx_tmpl_perm_tid ON master_role_template_permissions(template_id);
CREATE INDEX idx_tmpl_perm_pid ON master_role_template_permissions(permissionid);

-- SYSTEM_ADMIN: all SYSTEM permissions
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'SYSTEM_ADMIN' AND p.applicable_to = 'SYSTEM';

-- SYSTEM_SUPPORT: read-only + KYC review
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'SYSTEM_SUPPORT'
  AND p.permission_code IN ('SYS.CLIENT.READ','SYS.USER.READ','SYS.KYC.REVIEW',
      'SYS.AUDIT.READ','SYS.REPORT.VIEW','SYS.PAYMENT.READ','SYS.SETTINGS.READ');

-- SELLER_ADMIN: all SELLER permissions
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'SELLER_ADMIN' AND p.applicable_to = 'SELLER';

-- SELLER_MAKER: asset/auction/lot/workflow initiation + document upload
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'SELLER_MAKER'
  AND p.permission_code IN (
    'SELLER.ASSET.CREATE','SELLER.ASSET.READ','SELLER.ASSET.UPDATE',
    'SELLER.AUCTION.CREATE','SELLER.AUCTION.READ','SELLER.AUCTION.UPDATE',
    'SELLER.LOT.CREATE','SELLER.LOT.READ','SELLER.LOT.UPDATE',
    'SELLER.DOCUMENT.UPLOAD','SELLER.DOCUMENT.READ',
    'SELLER.WORKFLOW.CREATE','SELLER.WORKFLOW.READ',
    'SELLER.PAYMENT.READ','SELLER.REPORT.VIEW');

-- SELLER_CHECKER: approve/reject maker actions + read everything
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'SELLER_CHECKER'
  AND p.permission_code IN (
    'SELLER.ASSET.READ',
    'SELLER.AUCTION.READ','SELLER.AUCTION.APPROVE',
    'SELLER.LOT.READ',
    'SELLER.DOCUMENT.READ','SELLER.DOCUMENT.APPROVE',
    'SELLER.WORKFLOW.READ','SELLER.WORKFLOW.APPROVE','SELLER.WORKFLOW.REJECT',
    'SELLER.PAYMENT.READ','SELLER.REPORT.VIEW');

-- SELLER_VIEWER: all SELLER READ actions only
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'SELLER_VIEWER'
  AND p.applicable_to = 'SELLER' AND p.action IN ('READ','VIEW');

-- SELLER_AUDITOR: all reads + export
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'SELLER_AUDITOR'
  AND p.applicable_to = 'SELLER' AND p.action IN ('READ','VIEW','EXPORT');

-- SELLER_FINANCE_ADMIN: payment + invoice + reports
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'SELLER_FINANCE_ADMIN'
  AND p.permission_code IN (
    'SELLER.PAYMENT.READ','SELLER.PAYMENT.INITIATE','SELLER.PAYMENT.CONFIRM',
    'SELLER.REPORT.VIEW','SELLER.REPORT.EXPORT',
    'SELLER.AUCTION.READ','SELLER.LOT.READ','SELLER.DOCUMENT.READ');

-- SELLER_INDIVIDUAL: all SELLER except BRANCH, USER, ROLE management
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'SELLER_INDIVIDUAL'
  AND p.applicable_to = 'SELLER'
  AND p.resource NOT IN ('BRANCH','USER','ROLE');

-- BUYER_ADMIN: all BUYER permissions
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'BUYER_ADMIN' AND p.applicable_to = 'BUYER';

-- BUYER_BIDDER: bid + watchlist + auction access + payments/invoices
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'BUYER_BIDDER'
  AND p.permission_code IN (
    'BUYER.BID.PLACE','BUYER.BID.READ','BUYER.BID.RETRACT',
    'BUYER.WATCHLIST.ADD','BUYER.WATCHLIST.READ','BUYER.WATCHLIST.REMOVE',
    'BUYER.AUCTION.VIEW','BUYER.AUCTION.REGISTER',
    'BUYER.PAYMENT.READ','BUYER.INVOICE.READ','BUYER.INVOICE.DOWNLOAD',
    'BUYER.REPORT.VIEW');

-- BUYER_VIEWER: read-only
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'BUYER_VIEWER'
  AND p.permission_code IN (
    'BUYER.AUCTION.VIEW','BUYER.WATCHLIST.READ',
    'BUYER.INVOICE.READ','BUYER.PAYMENT.READ','BUYER.REPORT.VIEW');

-- BUYER_FINANCE_ADMIN: payment + invoice management
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'BUYER_FINANCE_ADMIN'
  AND p.permission_code IN (
    'BUYER.PAYMENT.READ','BUYER.PAYMENT.INITIATE','BUYER.PAYMENT.CONFIRM',
    'BUYER.INVOICE.READ','BUYER.INVOICE.DOWNLOAD',
    'BUYER.REPORT.VIEW','BUYER.REPORT.EXPORT');

-- BUYER_AUDITOR: all reads + export
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'BUYER_AUDITOR'
  AND p.applicable_to = 'BUYER' AND p.action IN ('READ','VIEW','EXPORT','DOWNLOAD');

-- BUYER_INDIVIDUAL: all BUYER except USER and ROLE management
INSERT INTO master_role_template_permissions (template_id, permissionid)
SELECT t.template_id, p.permissionid FROM master_role_templates t
CROSS JOIN master_permissions p
WHERE t.template_code = 'BUYER_INDIVIDUAL'
  AND p.applicable_to = 'BUYER'
  AND p.resource NOT IN ('USER','ROLE');

-- ============================================================
-- RBAC: TENANT ROLES
-- ============================================================
CREATE TABLE master_roles (
    roleid        INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientid      INTEGER      REFERENCES client_register(clientid),
    template_id   INTEGER      REFERENCES master_role_templates(template_id),
    role_code     VARCHAR(60)  NOT NULL,
    role_name     VARCHAR(100) NOT NULL,
    description   VARCHAR(500),
    actor_type    VARCHAR(10)  NOT NULL CHECK (actor_type IN ('SYSTEM','SELLER','BUYER')),
    client_type   VARCHAR(10)  NOT NULL DEFAULT 'BOTH' CHECK (client_type IN ('COMPANY','INDIVIDUAL','BOTH')),
    source        VARCHAR(20)  NOT NULL DEFAULT 'CLIENT_CUSTOM'
                               CHECK (source IN ('SYSTEM_TEMPLATE','CLIENT_CLONED','CLIENT_CUSTOM')),
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    status        VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
    display_order SMALLINT     NOT NULL DEFAULT 0,
    created_by    INTEGER      REFERENCES user_register(userid),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ,
    updated_by    INTEGER      REFERENCES user_register(userid),
    CONSTRAINT uq_role_client_code UNIQUE (clientid, role_code)
);

CREATE INDEX idx_role_client ON master_roles(clientid, actor_type, is_active);
CREATE INDEX idx_role_tmpl   ON master_roles(template_id) WHERE template_id IS NOT NULL;

-- ============================================================
-- RBAC: ROLE-PERMISSION MAPPING
-- ============================================================
CREATE TABLE role_permissions (
    id           INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roleid       INTEGER      NOT NULL REFERENCES master_roles(roleid)             ON DELETE CASCADE,
    permissionid INTEGER      NOT NULL REFERENCES master_permissions(permissionid) ON DELETE CASCADE,
    granted_by   INTEGER      REFERENCES user_register(userid),
    granted_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_role_perm UNIQUE (roleid, permissionid)
);

CREATE INDEX idx_rp_role ON role_permissions(roleid);
CREATE INDEX idx_rp_perm ON role_permissions(permissionid);

-- ============================================================
-- RBAC: USER-ROLE ASSIGNMENT
-- ============================================================
CREATE TABLE user_roles (
    id               INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid           INTEGER      NOT NULL REFERENCES user_register(userid)      ON DELETE CASCADE,
    roleid           INTEGER      NOT NULL REFERENCES master_roles(roleid),
    clientid         INTEGER      NOT NULL REFERENCES client_register(clientid),
    branchid         INTEGER      REFERENCES client_branches(branchid)           ON DELETE SET NULL,
    is_primary       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_branch_scoped BOOLEAN      NOT NULL DEFAULT FALSE,
    status           VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE','REVOKED')),
    assigned_by      INTEGER      REFERENCES user_register(userid),
    assigned_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at       TIMESTAMPTZ,
    revoked_at       TIMESTAMPTZ,
    revoked_by       INTEGER      REFERENCES user_register(userid)
);

CREATE UNIQUE INDEX uq_user_role_global ON user_roles(userid, roleid)           WHERE branchid IS NULL;
CREATE UNIQUE INDEX uq_user_role_branch ON user_roles(userid, roleid, branchid) WHERE branchid IS NOT NULL;
CREATE        INDEX idx_ur_userid       ON user_roles(userid,   status);
CREATE        INDEX idx_ur_roleid       ON user_roles(roleid);
CREATE        INDEX idx_ur_clientid     ON user_roles(clientid, status);
CREATE        INDEX idx_ur_branch       ON user_roles(branchid) WHERE branchid IS NOT NULL;


-- 9. PASSWORD HISTORY
CREATE TABLE IF NOT EXISTS user_password_history (
    passhistoryid INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    userid INTEGER NOT NULL REFERENCES user_register(userid),
    password_hash VARCHAR(500) NOT NULL,
    password_salt VARCHAR(100),
    changed_at TIMESTAMPTZ,
    changed_by INTEGER,
    reason VARCHAR(25) CHECK (reason IN ('ADMIN_RESET','EXPIRED','FORCED_CHANGE','SECURITY_INCIDENT','USER_INITIATED'))
);

CREATE INDEX IF NOT EXISTS idx_password_history_userid ON user_password_history(userid);


-- 10. LOGIN ATTEMPTS & SECURITY
CREATE TABLE IF NOT EXISTS user_login_attempts (
    id                 INTEGER          GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    userid             INTEGER          REFERENCES user_register(userid),
    username           VARCHAR(100),
    client_id          INTEGER          REFERENCES client_register(clientid),
    attempt_type       VARCHAR(15)      CHECK (attempt_type IN ('FAILED','LOCKED','SUCCESS')),
    platform           VARCHAR(20) CHECK (platform IN ('API','DESKTOP','MOBILE_ANDROID','MOBILE_IOS','WEB')),
    session_id         TEXT,
    jti                UUID,
    ip_address         VARCHAR(45),
    user_agent         TEXT,
    device_fingerprint VARCHAR(255),
    app_version        VARCHAR(50),
    location_city      VARCHAR(100),
    location_country   VARCHAR(100),
    latitude           DECIMAL(10, 8),
    longitude          DECIMAL(11, 8),
    failure_reason     TEXT,
    is_suspicious      BOOLEAN          DEFAULT FALSE,
    risk_score         SMALLINT         DEFAULT 0 CHECK (risk_score BETWEEN 0 AND 100),
    timestamp          TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_user_login_attempts_userid     ON user_login_attempts(userid);
CREATE INDEX IF NOT EXISTS idx_user_login_attempts_timestamp  ON user_login_attempts(timestamp);
CREATE INDEX IF NOT EXISTS idx_user_login_attempts_platform   ON user_login_attempts(platform);
CREATE INDEX IF NOT EXISTS idx_user_login_attempts_jti        ON user_login_attempts(jti)              WHERE jti IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_user_login_attempts_suspicious ON user_login_attempts(userid, timestamp DESC) WHERE is_suspicious = TRUE;

-- 11. FAILED LOGIN TRACKING
-- FIX: original had CHECK (platform IN ...) â€” column is last_attempt_platform
CREATE TABLE IF NOT EXISTS user_failed_logins (
    id                           INTEGER      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    userid                       INTEGER      NOT NULL REFERENCES user_register(userid),
    failed_attempt_count         INT          DEFAULT 0,
    last_failed_attempt          TIMESTAMPTZ,
    last_attempt_ip              VARCHAR(45),
    last_attempt_platform        VARCHAR(20) CHECK (last_attempt_platform IN ('API','DESKTOP','MOBILE_ANDROID','MOBILE_IOS','WEB')),
    account_locked               BOOLEAN      DEFAULT FALSE,
    lock_until                   TIMESTAMPTZ,
    lock_reason                  VARCHAR(255),
    unlock_token                 VARCHAR(255),
    auto_unlock_token_expires_at TIMESTAMPTZ,
    notify_sent                  BOOLEAN      DEFAULT FALSE,
    notify_sent_at               TIMESTAMPTZ,
    created_at                   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   TIMESTAMPTZ
);


-- 12. DEVICE REGISTRATION & MANAGEMENT
CREATE TABLE IF NOT EXISTS user_devices (
    id                      INTEGER      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    user_id                 INTEGER      NOT NULL REFERENCES user_register(userid),
    client_id               INTEGER      REFERENCES client_register(clientid),
    device_id               VARCHAR(255) NOT NULL,
    device_type             VARCHAR(10)  CHECK (device_type IN ('DESKTOP','MOBILE','OTHER','TABLET')),
    device_name             VARCHAR(255),
    device_manufacturer     VARCHAR(100),
    os_type                 VARCHAR(10)  CHECK (os_type IN ('ANDROID','IOS','LINUX','MAC','WINDOWS')),
    os_version              VARCHAR(50),
    browser_name            VARCHAR(100),
    browser_version         VARCHAR(50),
    push_token              TEXT,
    push_token_type         VARCHAR(10)  CHECK (push_token_type IN ('APNS','FCM','WEB_PUSH')),
    push_token_updated_at   TIMESTAMPTZ,
    app_version             VARCHAR(50),
    app_build_number        VARCHAR(50),
    screen_resolution       VARCHAR(20),
    network_type            VARCHAR(10)  CHECK (network_type IN ('2G','3G','4G','5G','ETHERNET','UNKNOWN','WIFI')),
    locale                  VARCHAR(20),
    timezone                VARCHAR(100),
    is_rooted_jailbroken    BOOLEAN      DEFAULT FALSE,
    location_permission     BOOLEAN      DEFAULT FALSE,
    notification_permission BOOLEAN      DEFAULT FALSE,
    ip_address              VARCHAR(45),
    mac_address             VARCHAR(17),
    device_token            VARCHAR(255),
    is_trusted              BOOLEAN      DEFAULT FALSE,
    is_revoked              BOOLEAN      DEFAULT FALSE,
    registered_at           TIMESTAMPTZ,
    last_used_at            TIMESTAMPTZ,
    revoked_at              TIMESTAMPTZ,
    revoked_reason          VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_device_user_id    ON user_devices(user_id);
CREATE INDEX IF NOT EXISTS idx_device_device_id  ON user_devices(device_id);
CREATE INDEX IF NOT EXISTS idx_device_client     ON user_devices(client_id);
CREATE INDEX IF NOT EXISTS idx_device_push_token ON user_devices(push_token)  WHERE push_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_device_rooted     ON user_devices(user_id)     WHERE is_rooted_jailbroken = TRUE;


-- 13. USER SESSIONS
CREATE TABLE IF NOT EXISTS user_sessions (
    id                       INTEGER          GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    session_id               TEXT             NOT NULL UNIQUE,
    user_id                  INTEGER          NOT NULL REFERENCES user_register(userid),
    client_id                INTEGER          REFERENCES client_register(clientid),
    device_id                INTEGER          REFERENCES user_devices(id) ON DELETE SET NULL,
    jti                      UUID,
    token                    TEXT             NOT NULL,
    refresh_token            TEXT,
    token_type               VARCHAR(50)      DEFAULT 'JWT',
    refresh_token_expires_at TIMESTAMPTZ,
    refresh_count            SMALLINT         DEFAULT 0,
    last_refresh_at          TIMESTAMPTZ,
    platform                 VARCHAR(20) CHECK (platform IN ('API','DESKTOP','MOBILE_ANDROID','MOBILE_IOS','WEB')),
    app_version              VARCHAR(50),
    app_state                VARCHAR(20)      DEFAULT 'ACTIVE',
    ip_address               VARCHAR(45),
    user_agent               TEXT,
    location_city            VARCHAR(100),
    location_country         VARCHAR(100),
    latitude                 DECIMAL(10, 8),
    longitude                DECIMAL(11, 8),
    created_at               TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    issued_at                TIMESTAMPTZ,
    expires_at               TIMESTAMPTZ      NOT NULL,
    last_activity_at         TIMESTAMPTZ,
    is_active                BOOLEAN          DEFAULT TRUE,
    is_revoked               BOOLEAN          DEFAULT FALSE,
    revoked_at               TIMESTAMPTZ,
    revoke_reason            VARCHAR(255),
    logout_type              VARCHAR(20) CHECK (logout_type IN ('ADMIN_REVOKE','MANUAL','PASSWORD_CHANGE','SECURITY_EVENT','TIMEOUT','TOKEN_EXPIRED'))
);

CREATE INDEX IF NOT EXISTS idx_session_user_id    ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_session_token      ON user_sessions(token);
CREATE INDEX IF NOT EXISTS idx_session_session_id ON user_sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_session_jti        ON user_sessions(jti)        WHERE jti IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_session_platform   ON user_sessions(platform);
CREATE INDEX IF NOT EXISTS idx_session_active_exp ON user_sessions(expires_at) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_session_client     ON user_sessions(client_id);


CREATE TABLE IF NOT EXISTS user_token_audit (
    audit_id           INTEGER     GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    jti                UUID        NOT NULL,
    session_id         TEXT REFERENCES user_sessions(session_id) ON DELETE SET NULL,
    user_id            INTEGER     NOT NULL REFERENCES user_register(userid),
    client_id          INTEGER     REFERENCES client_register(clientid),
    token_action       VARCHAR(15) NOT NULL CHECK (token_action IN ('ISSUED','REFRESHED','REVOKED','EXPIRED','VALIDATED')),
    platform           VARCHAR(20) CHECK (platform IN ('API','DESKTOP','MOBILE_ANDROID','MOBILE_IOS','WEB')),
    ip_address         VARCHAR(45),
    user_agent         TEXT,
    device_fingerprint VARCHAR(255),
    issued_at          TIMESTAMPTZ,
    expires_at         TIMESTAMPTZ,
    revoked_at         TIMESTAMPTZ,
    revoke_reason      VARCHAR(30) CHECK (revoke_reason IN ('ADMIN_REVOKE','EXPIRED','LOGOUT','PASSWORD_CHANGE','ROLE_CHANGE','SECURITY_INCIDENT','SESSION_LIMIT_EXCEEDED','TOKEN_ROTATION')),
    claims_snapshot    JSONB,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_jwt_audit_jti       ON user_token_audit(jti);
CREATE INDEX IF NOT EXISTS idx_jwt_audit_user_date ON user_token_audit(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_jwt_audit_session   ON user_token_audit(session_id);
CREATE INDEX IF NOT EXISTS idx_jwt_audit_action    ON user_token_audit(token_action, created_at DESC);

-- JWT TOKEN BLACKLIST (Redis is primary; this is durable fallback)
CREATE TABLE IF NOT EXISTS user_token_blacklist (
    blacklist_id        INTEGER     GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    jti                 UUID        NOT NULL UNIQUE,
    user_id             INTEGER     NOT NULL REFERENCES user_register(userid),
    session_id         TEXT,
    revoked_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_by          INTEGER     REFERENCES user_register(userid),
    revoke_reason       VARCHAR(30) CHECK (revoke_reason IN ('ADMIN_REVOKE','EXPIRED','LOGOUT','PASSWORD_CHANGE','ROLE_CHANGE','SECURITY_INCIDENT','SESSION_LIMIT_EXCEEDED','TOKEN_ROTATION')),
    original_expires_at TIMESTAMPTZ NOT NULL,
    is_cleaned          BOOLEAN     DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_blacklist_jti     ON user_token_blacklist(jti);
CREATE INDEX IF NOT EXISTS idx_blacklist_cleanup ON user_token_blacklist(original_expires_at) WHERE is_cleaned = FALSE;
CREATE INDEX IF NOT EXISTS idx_blacklist_user    ON user_token_blacklist(user_id, revoked_at DESC);


-- SESSION ACTIVITY LOG
CREATE TABLE IF NOT EXISTS user_session_activity (
    activity_id       BIGINT      GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    session_id         TEXT NOT NULL REFERENCES user_sessions(session_id) ON DELETE CASCADE,
    user_id           INTEGER     NOT NULL REFERENCES user_register(userid),
    jti               UUID,
    activity_type     VARCHAR(30) NOT NULL CHECK (activity_type IN ('LOGIN','LOGOUT','PASSWORD_CHANGE','PROFILE_UPDATE','KYC_SUBMIT','DOCUMENT_UPLOAD','DOCUMENT_DOWNLOAD','AUCTION_VIEW','BID_PLACE','BID_RETRACT','PAYMENT_INITIATE','PAYMENT_CONFIRM','ROLE_ASSIGN','USER_CREATE','BRANCH_CREATE','SETTINGS_CHANGE','API_CALL','EXPORT','REPORT_VIEW')),
    http_method       VARCHAR(10),
    endpoint          VARCHAR(500),
    status_code       SMALLINT,
    duration_ms       INTEGER,
    request_id        UUID,
    ip_address        VARCHAR(45),
    geo_location      JSONB,
    is_mobile         BOOLEAN     DEFAULT FALSE,
    activity_metadata JSONB,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sal_session_date ON user_session_activity(session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sal_user_date    ON user_session_activity(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sal_jti          ON user_session_activity(jti) WHERE jti IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_sal_type_date    ON user_session_activity(activity_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sal_mobile       ON user_session_activity(is_mobile, created_at DESC) WHERE is_mobile = TRUE;


-- SESSION GEO HISTORY
CREATE TABLE IF NOT EXISTS user_session_geo (
    geo_id          INTEGER     GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    session_id         TEXT NOT NULL REFERENCES user_sessions(session_id) ON DELETE CASCADE,
    user_id         INTEGER     NOT NULL REFERENCES user_register(userid),
    ip_address      VARCHAR(45),
    city            VARCHAR(100),
    state_region    VARCHAR(100),
    country         VARCHAR(100),
    latitude        DECIMAL(10,8),
    longitude       DECIMAL(11,8),
    accuracy_meters DECIMAL(10,2),
    location_source VARCHAR(20) CHECK (location_source IN ('GPS','IP_GEOLOCATION','MANUAL','NETWORK')),
    is_anomalous    BOOLEAN     DEFAULT FALSE,
    anomaly_reason  TEXT,
    recorded_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_geo_session_time ON user_session_geo(session_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_geo_anomalies    ON user_session_geo(user_id, recorded_at DESC) WHERE is_anomalous = TRUE;


-- SESSION REPORT SUMMARY
CREATE TABLE IF NOT EXISTS user_session_summary (
    report_id                INTEGER     GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    session_id         TEXT UNIQUE REFERENCES user_sessions(session_id) ON DELETE SET NULL,
    user_id                  INTEGER     NOT NULL REFERENCES user_register(userid),
    client_id                INTEGER     REFERENCES client_register(clientid),
    session_date             DATE        NOT NULL,
    platform                 VARCHAR(20) CHECK (platform IN ('API','DESKTOP','MOBILE_ANDROID','MOBILE_IOS','WEB')),
    is_mobile                BOOLEAN     DEFAULT FALSE,
    session_start            TIMESTAMPTZ,
    session_end              TIMESTAMPTZ,
    session_duration_seconds INTEGER,
    total_actions            INTEGER     DEFAULT 0,
    total_api_calls          INTEGER     DEFAULT 0,
    total_auction_views      INTEGER     DEFAULT 0,
    total_bids_placed        INTEGER     DEFAULT 0,
    total_payments           INTEGER     DEFAULT 0,
    total_document_downloads INTEGER     DEFAULT 0,
    tokens_issued            INTEGER     DEFAULT 0,
    tokens_refreshed         INTEGER     DEFAULT 0,
    tokens_revoked           INTEGER     DEFAULT 0,
    suspicious_activity_count INTEGER    DEFAULT 0,
    unique_ips_used          INTEGER     DEFAULT 1,
    has_anomalous_geo        BOOLEAN     DEFAULT FALSE,
    logout_type              VARCHAR(20) CHECK (logout_type IN ('ADMIN_REVOKE','MANUAL','PASSWORD_CHANGE','SECURITY_EVENT','TIMEOUT','TOKEN_EXPIRED')),
    generated_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_srs_user_date   ON user_session_summary(user_id, session_date DESC);
CREATE INDEX IF NOT EXISTS idx_srs_client_date ON user_session_summary(client_id, session_date DESC);
CREATE INDEX IF NOT EXISTS idx_srs_platform    ON user_session_summary(platform, session_date DESC);


-- CONCURRENT SESSION CONTROL
CREATE TABLE IF NOT EXISTS user_session_counts (
    user_id          INTEGER  PRIMARY KEY REFERENCES user_register(userid) ON DELETE CASCADE,
    active_count     SMALLINT NOT NULL DEFAULT 0,
    web_count        SMALLINT NOT NULL DEFAULT 0,
    mobile_count     SMALLINT NOT NULL DEFAULT 0,
    last_session_id         TEXT,
    last_activity_at TIMESTAMPTZ,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_counts_nonneg CHECK (active_count >= 0 AND web_count >= 0 AND mobile_count >= 0),
    CONSTRAINT chk_counts_total  CHECK (active_count = web_count + mobile_count)
);


-- 14. SECURITY CONFIGURATION (Per Tenant)
CREATE TABLE user_security_configs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    client_id INTEGER NOT NULL UNIQUE REFERENCES client_register(clientid),
    password_min_length INT DEFAULT 8,
    password_max_length INT DEFAULT 128,
    password_require_uppercase BOOLEAN DEFAULT TRUE,
    password_require_lowercase BOOLEAN DEFAULT TRUE,
    password_require_numbers BOOLEAN DEFAULT TRUE,
    password_require_special_chars BOOLEAN DEFAULT TRUE,
    password_special_chars_regex VARCHAR(255) DEFAULT '!@#$%^&*()',
    password_expiry_days INT DEFAULT 90,
    password_history_count INT DEFAULT 5,
    password_policy_regex TEXT,
    mfa_required BOOLEAN DEFAULT FALSE,
    mfa_type VARCHAR(25) CHECK (mfa_type IN ('DISABLED','OPTIONAL','REQUIRED_ALL','REQUIRED_ADMIN','REQUIRED_FINANCE')),
    session_timeout_minutes INT DEFAULT 30,
    session_absolute_timeout_hours INT DEFAULT 8,
    max_concurrent_sessions INT DEFAULT 5,
    max_devices_allowed INT DEFAULT 3,
    max_failed_user_login_attempts INT DEFAULT 5,
    account_lockout_duration_minutes INT DEFAULT 30,
    ip_whitelist_enabled BOOLEAN DEFAULT FALSE,
    ip_blacklist_enabled BOOLEAN DEFAULT FALSE,
    device_verification_required BOOLEAN DEFAULT FALSE,
    force_password_change_on_first_login BOOLEAN DEFAULT TRUE,
    force_password_change_on_admin_reset BOOLEAN DEFAULT TRUE,
    password_change_notification BOOLEAN DEFAULT TRUE,
    login_notification BOOLEAN DEFAULT TRUE,
    suspicious_activity_notification BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ
);


-- 15. NOTIFICATION PREFERENCES
CREATE TABLE user_notification_preferences (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    userid INTEGER NOT NULL UNIQUE REFERENCES user_register(userid),
    email_notifications BOOLEAN DEFAULT TRUE,
    sms_notifications BOOLEAN DEFAULT FALSE,
    push_notifications BOOLEAN DEFAULT FALSE,
    wa_notifications BOOLEAN DEFAULT FALSE,
    login_alerts BOOLEAN DEFAULT TRUE,
    password_change_alerts BOOLEAN DEFAULT TRUE,
    device_registration_alerts BOOLEAN DEFAULT TRUE,
    role_change_alerts BOOLEAN DEFAULT TRUE,
    suspicious_activity_alerts BOOLEAN DEFAULT TRUE,
    auction_updates BOOLEAN DEFAULT TRUE,
    bidding_updates BOOLEAN DEFAULT TRUE,
    payment_updates BOOLEAN DEFAULT TRUE,
    notification_frequency VARCHAR(10) DEFAULT 'IMMEDIATE' CHECK (notification_frequency IN ('DAILY','IMMEDIATE','NEVER','WEEKLY')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ
);


-- 17. IP WHITELIST/BLACKLIST
CREATE TABLE user_ip_restrictions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES client_register(clientid),
    ip_address VARCHAR(45) NOT NULL,
    restriction_type VARCHAR(15) CHECK (restriction_type IN ('BLACKLIST','WHITELIST')),
    reason VARCHAR(255),
    created_by INTEGER REFERENCES user_register(userid),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT TRUE
);


-- ============================================================
-- BOOTSTRAP SEED â€” SYSTEM CLIENT + SUPER ADMIN USER
-- Runs once on first container start (empty volume).
--
-- Default credentials  â†’  username : superadmin
--                         password : Admin@123
--
-- Password is stored as BCrypt( rawPassword + password_salt ).
-- CHANGE IMMEDIATELY after first login in production.
-- To regenerate hash:
--   String raw  = "Admin@123" + salt;
--   String hash = new BCryptPasswordEncoder(12).encode(raw);
-- ============================================================

-- 1. SYSTEM client (company type â€” represents the platform itself)
INSERT INTO client_register (
    clientid, client_category, client_type,
    email_primary, registration_status, accountstatus,
    adminusername, created_at
) OVERRIDING SYSTEM VALUE VALUES (
    1, 'SYSTEM', 'COMPANY',
    'system@eauction.internal', 'ONBOARDING_COMPLETE', 'ACTIVE',
    'superadmin', CURRENT_TIMESTAMP
);

-- 2. Company profile for the SYSTEM client
INSERT INTO client_company_profile (
    clientid, company_name, company_name_short, company_type, created_at
) VALUES (
    1, 'eAuction Platform Pvt. Ltd.', 'eAuction', 'PRIVATE_LIMITED', CURRENT_TIMESTAMP
);

-- 3. Security policy for SYSTEM client
INSERT INTO user_security_configs (
    client_id,
    max_failed_user_login_attempts,
    account_lockout_duration_minutes,
    session_timeout_minutes,
    session_absolute_timeout_hours,
    force_password_change_on_first_login,
    mfa_required
) VALUES (
    1, 5, 30, 60, 8, TRUE, FALSE
);

-- 4. Root branch level (Head Office â€” admin branch, cannot be deleted)
INSERT INTO client_branch_levels (
    clientid, level_code, label, level_order, is_admin_branch, created_by
) VALUES (
    1, 'HO', 'Head Office', 1, TRUE, NULL
);

-- 5. Head Office branch
INSERT INTO client_branches (
    clientid, level_id, branch_code, branch_name,
    status, issystemgenerated, created_at
) VALUES (
    1,
    (SELECT level_id FROM client_branch_levels WHERE clientid = 1 AND level_code = 'HO'),
    'SYS-HO-001', 'System Head Office',
    'ACTIVE', TRUE, CURRENT_TIMESTAMP
);

-- 6. Super admin user
--    password_salt  : sys_bootstrap_salt_v1
--    BCrypt input   : Admin@123sys_bootstrap_salt_v1   (strength = 12)
--    password_hash  : replace this hash in production after running BCryptPasswordEncoder
INSERT INTO user_register (
    clientid,
    branchid,
    username,
    email,
    password_hash,
    password_salt,
    user_type,
    account_status,
    is_active,
    email_verified,
    force_password_change,
    version,
    created_at
) VALUES (
    1,
    (SELECT branchid FROM client_branches WHERE branch_code = 'SYS-HO-001'),
    'superadmin',
    'superadmin@eauction.internal',
    '$2a$12$5Qa9ahq2mQyCYV6walF15uW9sL5HUOIINcPht5DPIxSEEgCvWeOKK',
    'sys_bootstrap_salt_v1',
    'SYSTEM',
    'ACTIVE',
    TRUE,
    TRUE,
    TRUE,
    1,
    CURRENT_TIMESTAMP
);

-- 7. Super admin profile
INSERT INTO user_profiles (userid, first_name, last_name, designation, created_at)
VALUES (
    (SELECT userid FROM user_register WHERE username = 'superadmin'),
    'Super', 'Admin', 'Platform Administrator', CURRENT_TIMESTAMP
);

-- 8. Clone SYSTEM_ADMIN template â†’ tenant role for clientid=1
INSERT INTO master_roles (
    clientid, template_id, role_code, role_name, description,
    actor_type, client_type, source, is_system, is_active, status, created_at
) VALUES (
    1,
    (SELECT template_id FROM master_role_templates WHERE template_code = 'SYSTEM_ADMIN'),
    'SYSTEM_ADMIN',
    'System Administrator',
    'Full platform control â€” cloned from SYSTEM_ADMIN template',
    'SYSTEM', 'COMPANY', 'CLIENT_CLONED', TRUE, TRUE, 'ACTIVE', CURRENT_TIMESTAMP
);

-- 9. Copy all template permissions to the cloned role
INSERT INTO role_permissions (roleid, permissionid, granted_at)
SELECT
    (SELECT roleid FROM master_roles WHERE clientid = 1 AND role_code = 'SYSTEM_ADMIN'),
    mrtp.permissionid,
    CURRENT_TIMESTAMP
FROM master_role_template_permissions mrtp
WHERE mrtp.template_id = (
    SELECT template_id FROM master_role_templates WHERE template_code = 'SYSTEM_ADMIN'
);

-- 10. Assign SYSTEM_ADMIN role to superadmin user (tenant-wide, primary)
INSERT INTO user_roles (
    userid, roleid, clientid, branchid,
    is_primary, is_branch_scoped, status, assigned_at
) VALUES (
    (SELECT userid   FROM user_register WHERE username    = 'superadmin'),
    (SELECT roleid   FROM master_roles   WHERE clientid   = 1 AND role_code = 'SYSTEM_ADMIN'),
    1,
    (SELECT branchid FROM client_branches WHERE branch_code = 'SYS-HO-001'),
    TRUE, FALSE, 'ACTIVE', CURRENT_TIMESTAMP
);
